#!/bin/sh

# CLI replacements
alias \
    ls="eza --color=auto --icons" \
    cd="z" \
    cat="bat" \
    du="ncdu" \
    find="fd" \
    df="duf"

# Colorized commands
alias \
    dir="dir --color=auto" \
    vdir="vdir --color=auto" \
    grep="grep --color=auto" \
    fgrep="fgrep --color=auto" \
    egrep="egrep --color=auto" \
    diff="diff --color=auto" \
    ccat="highlight --out-format=ansi" \
    dfg="df -BG" \
    dfm="df -BM" \
    ip="ip --color=auto"

# LS aliases with preserved color flags
alias \
    ll="ls -l" \
    la="ls -A" \
    llt="ls -la -tmodified -r -G"

# Package management
# TODO: Add aura here
alias \
    flinst="flatpak install" \
    flrem="flatpak uninstall --delete-data" \
    flclean="flatpak uninstall --unused --delete-data -y && flatpak repair"

# Network aliases
alias \
    rsync="rsync -avh --progress" \
    rsync-ssh="rsync -avzh --progress -e ssh" \
    rsync-net="rsync -avzh --progress" \
    gcl='git clone --depth 1' \
    nfs-mount="sudo mount -t nfs -o soft,timeo=50,retrans=2,intr,noac" \
    ssh-mount="sshfs -o reconnect,ServerAliveInterval=15,ServerAliveCountMax=3,sshfs_sync"

# Safe file operations
alias \
    cp="cp -iv" \
    mv="mv -iv" \
    rm="rm -vI" \
    mkd="mkdir -pv" \
    clear="tput clear" \
    reset="tput reset"

# System utilities
alias \
    pyserv="python3 -m http.server" \
    pyenv="python -m venv" \
    reset="tput reset" \
    update="aura -Syu && aura -Au"

# Gaming
alias \
    cleanup-gamescope='pkill -9 -f "wine|wineserver|winedevice.exe|explorer.exe|gamescope-wl"' \
    gscontroller="LD_PRELOAD='' gamescope -h 1080 -H 1080 -f --adaptive-sync --immediate-flips --force-grab-cursor --mangoapp"

# Version control
alias gcl='git clone --depth 1'

# Use neovim if available
command -v nvim >/dev/null && alias vim="nvim" vimdiff="nvim -d"

# XDG-compliant tmux configuration
alias tmux="tmux -f ${XDG_CONFIG_HOME:-$HOME/.config}/tmux/tmux.conf"
